name: clima_prub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^10.1.1
  connectivity_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/weather_icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icono.png"
 
